services:
  livemenu-service:
    container_name: livemenu_service
    build: ./backend/server
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres-db:5432/livemenu_db
      - spring.datasource.username=admin
      - spring.datasource.password=postgres
      - spring.data.redis.host=redis-cache
      - spring.security.jwt.secret=${JWT_SECRET}
      - cloudinary.url=${CN_URL}
      - firebase.config=${FIREBASE_CONFIG}

  postgres-db:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: livemenu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: